### PR TITLE
Enhance Docker and FastAPI Configuration with Headless Chromium Support

### PR DESCRIPTION
**Pull request by gandrunx**
This pull request introduces several key enhancements to the FastAPI application and Docker setup:

1. **Headless Chromium Support:**
   - Added `--headless` argument to `server.py` to allow Chromium to run in headless mode. This can be toggled with the `--headless` argument when starting the application, with `true` as the default value.

2. **Improved Error Handling and Defaults:**
   - Updated `server.py` to handle default values for logging and headless mode more robustly. Added `--remote-debugging-port=9222` and `--no-sandbox` flags to Chromium options to ensure compatibility in Docker environments.

3. **Dockerfile Updates:**
   - Enhanced Dockerfile to install necessary Chromium dependencies and handle Chromium installation, including `libu2f-udev` and `libvulkan1` libraries.

4. **.gitignore File Addition:**
   - Added a `.gitignore` file to exclude common unnecessary files and directories from version control, including Python cache files, virtual environments, and IDE-specific configurations.

**Details:**

- **`server.py` Adjustments:**
  - Integrated argument parsing for `--headless` and `--nolog` with default values.
  - Configured Chromium options to include `--remote-debugging-port=9222` and `--no-sandbox` for Docker compatibility.
  - Enhanced error handling to ensure cleaner operation.

- **Dockerfile Improvements:**
  - Added commands to install Chromium along with necessary system libraries.
  - Set up the working directory and updated `pip` dependencies.

- **`.gitignore` Additions:**
  - Excluded Python cache files, virtual environments, Docker logs, and IDE-specific files.

**Issue Reference:**

- Addresses issue #17 

**Note:**

Please be aware that additional code adjustments might be needed to ensure full compatibility with Docker environments. If you encounter issues or need further assistance with Docker configurations, feel free to reach out for support.

### CODE REVIEW

**Comment by sarperavci** [comment]
Thanks for your contribution. When I build and run it, I encounter these errors. Can the container bypass the verification on your side?

```sh
sarp@IdeaPad:~/Desktop/CloudflareBypassForScraping-add-docker$ docker run -p 8001:8000 cf
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
Error clicking verification button: 'NoneType' object is not callable
Attempt 1: Verification page detected. Trying to bypass...
Error clicking verification button: 原来获取到的元素对象已不在页面内。
Attempt 2: Verification page detected. Trying to bypass...
Verification button found. Attempting to click.
Attempt 3: Verification page detected. Trying to bypass...
Verification button found. Attempting to click.
Attempt 4: Verification page detected. Trying to bypass...
Verification button found. Attempting to click.
Attempt 5: Verification page detected. Trying to bypass...
^CVerification button found. Attempting to click.
Attempt 6: Verification page detected. Trying to bypass...
Basic search failed. Searching for button recursively.
Error clicking verification button: 页面被刷新，请操作前尝试等待页面刷新或加载完成。
Exceeded maximum retries. Bypass failed.
Bypass failed.
INFO:     172.17.0.1:61974 - "GET /cookies?url=https://nopecha.com/demo/cloudflare HTTP/1.1" 200 OK
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [1]
```

**Comment by sarperavci** [comment]
In addition, the `server.py` does not work on my Ubuntu environment. I think it’s related to headless mode. Cloudflare detects that it’s not a real browser and completely blocks it. I commented out lines 58 and 59 in `server.py`, and it worked in my environment but not in the container environment as expected.

```python
# Function to bypass Cloudflare protection
def bypass_cloudflare(url: str, retries: int, headless: bool) -> ChromiumPage:
    options = ChromiumOptions()
    options.set_argument("--auto-open-devtools-for-tabs", "true")
    options.set_argument("--remote-debugging-port=9222")
    #if headless: # LINE 58
    #    options.set_argument("--headless") # LINE 59
    options.set_argument("--no-sandbox")  # Add no-sandbox for Docker environments
    options.set_paths(browser_path=browser_path)

    driver = ChromiumPage(addr_or_opts=options)
    try:
        driver.get(url)
        cf_bypasser = CloudflareBypasser(driver, retries, log)
        cf_bypasser.bypass()
        return driver
    except Exception as e:
        driver.quit()
        raise e
```

**Comment by gandrunx** [comment]
Thank you for the feedback. I’ll work on fixing the issue. It seems that the problem is related to headless mode and Cloudflare’s detection. I’ll review the server.py configuration and ensure that the headless settings are appropriate for both the local environment and the container environment. Please bear with me, and I’ll update you once the fix is implemented.

**Comment by sarperavci** [comment]
An unmatched work! Thank's for your contributing. I am merging your PR.

**Comment by sarperavci** [comment]
An unmatched work! Thanks for your contribution. I am merging your PR.

**Pull request merged**
